trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:

# 🔹 BUILD STAGE
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean package'

# 🔹 TEST STAGE
- stage: Test
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: TestJob
    steps:
    - task: Maven@4
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: '**/surefire-reports/TEST-*.xml'